"""add cols to vpn server table

Revision ID: 17af1e8e6c7c
Revises: cc4fa7ce61a4
Create Date: 2024-12-06 15:12:51.493721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17af1e8e6c7c"
down_revision: Union[str, None] = "cc4fa7ce61a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pushka_vpn_tariff",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.add_column(
        "pushka_vpn_vpn_server",
        sa.Column(
            "cookies", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "pushka_vpn_vpn_server", sa.Column("type", sa.String(), nullable=True)
    )
    op.add_column(
        "pushka_vpn_vpn_server",
        sa.Column("security", sa.String(), nullable=True),
    )
    op.add_column(
        "pushka_vpn_vpn_server", sa.Column("pbk", sa.String(), nullable=True)
    )
    op.add_column(
        "pushka_vpn_vpn_server", sa.Column("fp", sa.String(), nullable=True)
    )
    op.add_column(
        "pushka_vpn_vpn_server", sa.Column("sni", sa.String(), nullable=True)
    )
    op.add_column(
        "pushka_vpn_vpn_server", sa.Column("sid", sa.String(), nullable=True)
    )
    op.add_column(
        "pushka_vpn_vpn_server", sa.Column("spx", sa.String(), nullable=True)
    )
    op.add_column(
        "pushka_vpn_vpn_server", sa.Column("flow", sa.String(), nullable=True)
    )
    op.add_column(
        "pushka_vpn_vpn_server", sa.Column("port", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pushka_vpn_vpn_server", "flow")
    op.drop_column("pushka_vpn_vpn_server", "spx")
    op.drop_column("pushka_vpn_vpn_server", "sid")
    op.drop_column("pushka_vpn_vpn_server", "sni")
    op.drop_column("pushka_vpn_vpn_server", "fp")
    op.drop_column("pushka_vpn_vpn_server", "pbk")
    op.drop_column("pushka_vpn_vpn_server", "security")
    op.drop_column("pushka_vpn_vpn_server", "type")
    op.drop_column("pushka_vpn_vpn_server", "cookies")
    op.drop_column("pushka_vpn_vpn_server", "port")
    op.alter_column(
        "pushka_vpn_tariff",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###
