"""server_id for user link

Revision ID: 5f7a5051d598
Revises: fc828fc6fd9c
Create Date: 2024-12-13 18:33:07.720117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7a5051d598'
down_revision: Union[str, None] = 'fc828fc6fd9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushka_vpn_user_link', sa.Column('server_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'pushka_vpn_user_link', 'pushka_vpn_vpn_server', ['server_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pushka_vpn_user_link', type_='foreignkey')
    op.drop_column('pushka_vpn_user_link', 'server_id')
    # ### end Alembic commands ###
