"""change user link relation

Revision ID: 9a03c1bd9a69
Revises: 17af1e8e6c7c
Create Date: 2024-12-10 19:04:16.289142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a03c1bd9a69'
down_revision: Union[str, None] = '17af1e8e6c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pushka_vpn_user', 'subscription_expire_date')
    op.add_column('pushka_vpn_user_link', sa.Column('expire_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'pushka_vpn_user_link', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pushka_vpn_user_link', type_='unique')
    op.drop_column('pushka_vpn_user_link', 'expire_date')
    op.add_column('pushka_vpn_user', sa.Column('subscription_expire_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
