"""first commit

Revision ID: f524536eedbf
Revises: 
Create Date: 2024-12-03 15:04:03.159606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f524536eedbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('new', 'trial', 'free', 'paid', 'not_paid', name='statustypeenum').create(op.get_bind())
    op.create_table('pushka_vpn_tariff',
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pushka_vpn_user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='User ID in Telegram'),
    sa.Column('status', postgresql.ENUM('new', 'trial', 'free', 'paid', 'not_paid', name='statustypeenum', create_type=False), nullable=False, comment='Transaction source type'),
    sa.Column('link', sa.String(), nullable=True, comment='VPN link'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pushka_vpn_user_tariff',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pushka_vpn_user_tariff')
    op.drop_table('pushka_vpn_user')
    op.drop_table('pushka_vpn_tariff')
    sa.Enum('new', 'trial', 'free', 'paid', 'not_paid', name='statustypeenum').drop(op.get_bind())
    # ### end Alembic commands ###
