"""client_id and sub_id for user link

Revision ID: fc828fc6fd9c
Revises: 9a03c1bd9a69
Create Date: 2024-12-11 11:02:48.187136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc828fc6fd9c'
down_revision: Union[str, None] = '9a03c1bd9a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushka_vpn_user_link', sa.Column('client_id', sa.UUID(), nullable=False, comment='VPN client ID'))
    op.add_column('pushka_vpn_user_link', sa.Column('client_sub_id', sa.UUID(), nullable=False, comment='VPN client ID'))
    op.create_unique_constraint(None, 'pushka_vpn_user_link', ['client_id'])
    op.create_unique_constraint(None, 'pushka_vpn_user_link', ['client_sub_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pushka_vpn_user_link', type_='unique')
    op.drop_constraint(None, 'pushka_vpn_user_link', type_='unique')
    op.drop_column('pushka_vpn_user_link', 'client_sub_id')
    op.drop_column('pushka_vpn_user_link', 'client_id')
    # ### end Alembic commands ###
